### PR TITLE
rocker: add freedreno to the gallium drivers list

### PR DESCRIPTION
**Pull request by tanty**
Signed-off-by: Andres Gomez <agomez@igalia.com>

### CODE REVIEW

**Comment by tanty** [comment]
Any reason why we weren't building freedreno?

Please, check also the need to add it for the Android build. I didn't have a clue about that.

**Comment by jasuarez** [comment]
> Any reason why we weren't building freedreno?

Probably because we forgot?

Jokes apart, probably we should take a look again about the options used in upstream. Probably we want to add some new options in our build system. I'm thinking on enabling dri3, for instance.

**Review by jasuarez — APPROVED** [review]
Looks good for me.

Yes, I think we need to add it also in Android build. I think I didn't add it before because the original build didn't had it neither.

**Comment by tanty** [comment]
Updated, please, review and rebase and merge if it looks OK for you :smiley:

**Review by jasuarez — APPROVED** [review]
OK

**Pull request merged**
